blank_issues_enabled: false
contact_links:
  - name: Ask a question（提问和讨论）
    url: https://user-images.githubusercontent.com/33956589/144778828-97660d67-69a1-4eee-8ef1-3c7f91ab48b9.png
    about: Add this WeChat(HIJNTIYou), we will invite you to the WeChat discussion group later
