name: Issues Similarity Analysis

on:
  issues:
    types: [opened, edited]

jobs:
  analysis:
    runs-on: ubuntu-latest
    steps:
      - name: analysis
        uses: actions-cool/issues-similarity-analysis@main
        with:
          filter-threshold: 0.5
          comment-title: '### 希望下面可以帮助到你'
          comment-body: '${index}. ${similarity} #{number} '
