name: Issue Month Statistics

on:
  issues:
    types: [labeled]

jobs:
  month-statistics:
    runs-on: ubuntu-latest
    steps:
      - name: month-statistics
        if: github.event.label.name == 'month-statistics'
        uses: actions/checkout@master
        with:
          actions: "month-statistics"
          token: ${{ secrets.GITHUB_TOKEN }}
          labels: "month-statistics"
          count-lables: "true"
          count-comments: "true"
