name: Issue Mark Duplicate

on:
  issue_comment:
    types: [created]

jobs:
  mark-duplicate:
    runs-on: ubuntu-latest
    steps:
      - name: mark-duplicate
        uses: actions-cool/issues-helper@v1.7
        with:
          actions: 'mark-duplicate'
          token: ${{ secrets.GH }}
          duplicate-labels: 'duplicate'
          close-issue: true
