name: Issue Add Inactive

on:
  issues:
    types: [labeled]

jobs:
  close-issues:
    runs-on: ubuntu-latest
    steps:
      - name: close-issues
        if: github.event.label.name == 'check-inactive'
        uses: actions-cool/issues-helper@up
        with:
          actions: 'check-inactive'
