name: Issue Mark Duplicate

on:
  issue_comment:
    types: [created, edited]

jobs:
  mark-duplicate:
    runs-on: ubuntu-latest
    steps:
      - name: mark-duplicate
        uses: actions-cool/issues-helper@add-duplicate
        with:
          actions: 'mark-duplicate'
          token: ${{ secrets.GH }}
          labels: 'x1,x2'
          contents: '+1, -1'
