name: Issue Mark Duplicate

on:
  issue_comment:
    types: [created, edited]

jobs:
  mark-duplicate:
    runs-on: ubuntu-latest
    steps:
      - name: mark-duplicate
        uses: actions-cool/issues-helper@v1.5
        with:
          actions: 'mark-duplicate'
          token: ${{ secrets.GH }}
          duplicate-command: '/s'
          duplicate-labels: 'x21,x22'
          contents: '+1, -1'
