name: Issue Mark Duplicate

on:
  issue_comment:
    types: [created, edited]

jobs:
  mark-duplicate:
    runs-on: ubuntu-latest
    steps:
      - name: mark-duplicate
        uses: actions-cool/issues-helper@1.x
        with:
          actions: 'mark-duplicate'
          duplicate-labels: 'duplicate'
          remove-labels: 'status: needs triage,status: needs triage2'
          close-issue: true
