name: Find Comment

on:
  issues:
    types: [edited]

jobs:
  do-test:
    runs-on: ubuntu-latest
    steps:
      - name: find comments
        uses: actions-cool/issues-helper@fix
        id: fcid
        with:
          actions: 'find-comments'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body-includes: '<!-- AUTO_PREVIEW_HOOK -->'

      - run: echo random-number ${{ steps.fcid.outputs.comments }}
        shell: bash

      - name: create comment
        if: contains(steps.fcid.outputs.comments, '<!-- AUTO_PREVIEW_HOOK -->') == false
        uses: actions-cool/issues-helper@v2.1.1
        with:
          actions: 'create-comment'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: '<!-- AUTO_PREVIEW_HOOK --> err'

      - name: update comment
        if: contains(steps.fcid.outputs.comments, '<!-- AUTO_PREVIEW_HOOK -->') == true
        uses: actions-cool/issues-helper@v2.1.1
        with:
          actions: 'update-comment'
          token: ${{ secrets.GITHUB_TOKEN }}
          comment-id: ${{ steps.fcid.outputs.comments[0].id }}
          body: '<!-- AUTO_PREVIEW_HOOK --> Some error again!'
          update-mode: 'append'
