name: close need issues

on:
  issues:
    types: [labeled]

jobs:
  close-issues:
    runs-on: ubuntu-latest
    steps:
      - name: close-issues
        if: github.event.label.name == 'close-issues'
        uses: actions-cool/issues-helper@up
        with:
          actions: 'close-issues'
          token: ${{ secrets.GITHUB_TOKEN }}
          labels: '🤔 Need Reproduce'
