name: 🤖 Auto Make Release

on:
  create

jobs:
  make-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: install
        run: yarn

      - name: node js
        run: node ./script/make-release.js
        env:
          GH_TOKEN: ${{ secrets.GH }}
