name: PR Auto Label

on:
  pull_request_target:
    types: [opened, edited]

jobs:
  set-labels:
    runs-on: ubuntu-latest
    steps:
      - name: pr-auto-label
        uses: actions-cool/pr-auto-label@main
        with:
          enum: 'fix, feat, docs'
          format: 'pr-${type}'
          extra: 'feat/feature, docs/doc'
