name: Release Helper

on:
  create

jobs:
  release-helper:
    runs-on: ubuntu-latest
    steps:
      - name: make release
        if: github.event.ref_type == 'tag'
        uses: actions-cool/release-helper@main
        with:
          triger: 'tag'
          changelogs: 'CHANGELOG.en-US.md, CHANGELOG.zh-CN.md'
          branch: 'master'
          dingding-token: 123
          dingding-msg: 'CHANGELOG.zh-CN.md'
          dingding-ignore: '-, a, b, A, B'
