name: close help

on:
  schedule:
    - cron: "* * * * *"

jobs:
  close-issues:
    runs-on: ubuntu-latest
    steps:
      - name: close-issues
        uses: actions-cool/issue-helper@main
        with:
          actions: 'close-issues'
          token: ${{ secrets.GITHUB_TOKEN }}
          labels: 'help wanted'
