name: Check Issue

on:
  issues:
    types: [opened]

jobs:
  check-issue:
    runs-on: ubuntu-latest
    steps:
      - name: check-issue
        uses: actions-cool/issues-helper@up
        id: checkid
        with:
          actions: 'check-issue'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          title-includes: '官网,网站,国内,镜像,mobile ant design,mobile.ant.design,ant design,ant.design,pro/挂了,无法访问,不能访问,访问不了,出问题,打不开,登不上,can not open,can not be reached'

      - name: deal-website
        if: steps.checkid.outputs.check-result == 'true'
        uses: actions-cool/issues-helper@up
        with:
          actions: 'create-comment,close-issue'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            Ant Design 系列官网由于某些众所周知的原因无法访问，建议翻墙或访问国内镜像站点。
            
            ## 官网

            * Ant Design: https://ant.design
            * Ant Design Pro: https://pro.ant.design
            * Ant Design Pro Preview : https://preview.pro.ant.design
            * Ant Design Mobile: https://mobile.ant.design
            * Ant Motion: https://motion.ant.design

            ## 国内镜像

            * Ant Design: http://ant-design.gitee.io
            * Ant Design 3.x: http://ant-design-3x.gitee.io
            * Ant Design 2.x: http://ant-design-2x.gitee.io
            * Ant Design 1.x: http://ant-design-1x.gitee.io
            * Ant Design Pro: http://ant-design-pro.gitee.io
            * Ant Design Mobile: http://antd-mobile.gitee.io
            * Ant Motion: http://ant-motion.gitee.io
            * Ant Design Pro Preview : https://prosite.z23.web.core.windows.net
